language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kruegg21
  password:
    secure: h6gGFyl1Ps48qD0vSGNorwARbj1VjtNexYpAx/ya+vzdKf2eIxmgRq85OIBi5S9vBJyucSjPkdJtBV8HRkpGXC9E4C9Ty6Aff5DjHuyNOsF/BXPQVoffeDkkaX8R5VDZ5j0vvvbnKJyJQt8QEnawTOjuZHPJ69cVXeiCX9xKuh2aCTbZ6jhTdKBz1MYYu5a0UHxdPsC6INyxG+bvkdweTexEgJeU3/4nXIV18zZMZcIDq3f7FdYd5i3lGzwxcALCs+CyVuXf9Lj+gcdfeIDa6L7AeHMfrb5t7zxAgk548RY/lVSDgB4XYhOVlH7V0gDEYHxpYBj8OdFuJ2qx9EwgQksHo+6/7xV/BbDo52YQwxBFFfCg9NGWbR2qEjeGEKVIMan6fMvf+Y9OBgkzgussnRU+Jio+U/Es1zFt+JiKfH66qa5R7icWkbcCxMIPtdyd4vZQ8TD2Sln2ZCf0Ru+AgQZzHFnkoLOeTRbwl6k9XafU8JO4Yq0fx0IepPb1s3574iDIXd3V0ADlw7jZQjrh5ti/o5Fs7LHncUiyYWgfT++AN1ZenkTBsDs01hKNUFBwAHypOjUnsfypITUZR4wCE5NKT7LEcB0kVuYUxkxCYZz1CKnHZxhdX5Jn1isNLi9605m4DXVofJ7xdhNBfgDmpXOEc59m22hRdzc54VrNKcc=
  on:
    tags: true
    repo: kruegg21/word_neo4j
    python: 3.6
