language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kruegg21
  password:
    secure: wbwsU/+ZRGxyKAOrOdIpwhHGSizzcapGrv7m//lIDyaeiPlcWYrkOVTMvotvZAFcwI+dXkpzXDBnDjsuPJY7dPk/nTLSP9N3RVHlfE0Bsrq8I+d1XcO71gm43H6l7iHfN1JmesVMHPi59BqgSWjk0GjYONdH7IuLbrLxb9hL+01EGnTYMhRxjwe1vfdWTuebcdKrGCckyDIkYKGtPmde0L59O7nz8oT4oTr52rj+kAQmIaPmXctlTgoUj6SiM9Sw6u9u6a/om1klVvRF8S7BQs5MPWTND0pO99x1Lbj3tFcrNTb/Q39ud6/x4vfS4EXFXwri/7uuEJhlF29s0wcNbhmt7MMFawl744p/Enb3zBAm30ZkvTn81X/aeeGZXD1F7tyidYdoLYSDaDuXqXKaMmTFYnjTRgwFMCzFUMIh5G0YgUcD5jpK8iI9yK2K6Y8BczznQyNqWFeZ3SyVzYA06NS4NiAPSh3ZfXSHfMwMthk0PPQVbvJvapejRIzE7BpSOK5smmhWxTeX91zB8jzK1dnpDgy2Ujd3eJTKgEelr6pd0AkpERkn2Tn86XkN0HiAzMQY9UOIzaaaevB9rhwzvC/Ujrmk+6SYbt1fW/szJ19WzQ2igv/aPU/cLcwgG3mDhL2fMVtACTy1RJEEL347azvZ3AS8VjWJFGVfw8mF+40=
  on:
    tags: true
    repo: kruegg21/word_neo4j
    python: 3.6
