language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kruegg21
  password:
    secure: ycuKWE8BQavHPqIlKn84Sezame+b3fNetdWLKnmgWAL8gNTACzShTzhZ+ROOwy8IAgdLyXbcIMQMA1oO27F78LH/Fn8QJfIqyi+oCFI+KQK098xowv8z5gXZWR5pMwgz8Nly6p6FzchXJsOyojRfzLoO6bULggxw92v8wRNnyM6VHzgHIdhAKVWhFNSgzCrLN47G/2KIp5sW4QK4OECfD4MbPTlwOjuQBJECkb7qZLPm1fWhF1dPSf0K3MCfLHUz6d3rZBIH9fWDgTc4AxS33mwHEMwSSyBc6SGjUUBK6/aPVPdZucrTLgHA72ZPfwG0pMS7ueZmwi5n30d+ZtqrrzUee46yIuhNOfwSKaj0Cfp9AdmVs6RfGiJ1ATWKqa0rZLQVLRbqhMTO9fXwBUiK8p/gJmZzwKSleoG6qBMkaV2cL1frbHL/lPFtxtOJyrrc9rbtjS2W4pArmrQF70Vqx0GjRwdDy79ed61KiiNyDB1MK7B5VGWYBp2Xr0spFTnLO5H5nM97K+jh7bVDBGQ98yz4UVY9QGoQTJwSeN0dOUy9WsTIVRWyxmWFwmGx4aM4+EApnnCLJKmxQO4G7DtJT6WR/jzSl/AosI/D+jjQGpnKuO40oYww82QvSYHuOcmv6oqqWgcyCHru5fGb+TnaabHK5iwStOZm66xbbb5J57Q=
  on:
    tags: true
    repo: kruegg21/word_neo4j
    python: 3.6
